export const allCountriesEN = [
  { name: "Lithuania", flag: "https://flagcdn.com/lt.svg", cca2: "LT" },
  { name: "Chile", flag: "https://flagcdn.com/cl.svg", cca2: "CL" },
  { name: "Benin", flag: "https://flagcdn.com/bj.svg", cca2: "BJ" },
  {
    name: "Falkland Islands",
    flag: "https://flagcdn.com/fk.svg",
    cca2: "FK",
  },
  { name: "Georgia", flag: "https://flagcdn.com/ge.svg", cca2: "GE" },
  { name: "Cyprus", flag: "https://flagcdn.com/cy.svg", cca2: "CY" },
  { name: "Ghana", flag: "https://flagcdn.com/gh.svg", cca2: "GH" },
  { name: "Belgium", flag: "https://flagcdn.com/be.svg", cca2: "BE" },
  { name: "Cuba", flag: "https://flagcdn.com/cu.svg", cca2: "CU" },
  { name: "Andorra", flag: "https://flagcdn.com/ad.svg", cca2: "AD" },
  { name: "Argentina", flag: "https://flagcdn.com/ar.svg", cca2: "AR" },
  { name: "El Salvador", flag: "https://flagcdn.com/sv.svg", cca2: "SV" },
  { name: "Uzbekistan", flag: "https://flagcdn.com/uz.svg", cca2: "UZ" },
  { name: "Belize", flag: "https://flagcdn.com/bz.svg", cca2: "BZ" },
  { name: "Latvia", flag: "https://flagcdn.com/lv.svg", cca2: "LV" },
  { name: "Ivory Coast", flag: "https://flagcdn.com/ci.svg", cca2: "CI" },
  { name: "France", flag: "https://flagcdn.com/fr.svg", cca2: "FR" },
  {
    name: "Northern Mariana Islands",
    flag: "https://flagcdn.com/mp.svg",
    cca2: "MP",
  },
  {
    name: "Republic of the Congo",
    flag: "https://flagcdn.com/cg.svg",
    cca2: "CG",
  },
  { name: "Bangladesh", flag: "https://flagcdn.com/bd.svg", cca2: "BD" },
  { name: "Palau", flag: "https://flagcdn.com/pw.svg", cca2: "PW" },
  {
    name: "Afghanistan",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    cca2: "AF",
  },
  { name: "Ethiopia", flag: "https://flagcdn.com/et.svg", cca2: "ET" },
  { name: "New Caledonia", flag: "https://flagcdn.com/nc.svg", cca2: "NC" },
  { name: "Turkmenistan", flag: "https://flagcdn.com/tm.svg", cca2: "TM" },
  { name: "Jordan", flag: "https://flagcdn.com/jo.svg", cca2: "JO" },
  { name: "Montserrat", flag: "https://flagcdn.com/ms.svg", cca2: "MS" },
  { name: "Bulgaria", flag: "https://flagcdn.com/bg.svg", cca2: "BG" },
  { name: "Saint Lucia", flag: "https://flagcdn.com/lc.svg", cca2: "LC" },
  { name: "Senegal", flag: "https://flagcdn.com/sn.svg", cca2: "SN" },
  { name: "Uruguay", flag: "https://flagcdn.com/uy.svg", cca2: "UY" },
  { name: "Guinea-Bissau", flag: "https://flagcdn.com/gw.svg", cca2: "GW" },
  { name: "Philippines", flag: "https://flagcdn.com/ph.svg", cca2: "PH" },
  { name: "Tanzania", flag: "https://flagcdn.com/tz.svg", cca2: "TZ" },
  { name: "Isle of Man", flag: "https://flagcdn.com/im.svg", cca2: "IM" },
  { name: "Sudan", flag: "https://flagcdn.com/sd.svg", cca2: "SD" },
  { name: "Sierra Leone", flag: "https://flagcdn.com/sl.svg", cca2: "SL" },
  { name: "Chad", flag: "https://flagcdn.com/td.svg", cca2: "TD" },
  { name: "Vanuatu", flag: "https://flagcdn.com/vu.svg", cca2: "VU" },
  { name: "Rwanda", flag: "https://flagcdn.com/rw.svg", cca2: "RW" },
  { name: "Palestine", flag: "https://flagcdn.com/ps.svg", cca2: "PS" },
  { name: "Togo", flag: "https://flagcdn.com/tg.svg", cca2: "TG" },
  {
    name: "United Arab Emirates",
    flag: "https://flagcdn.com/ae.svg",
    cca2: "AE",
  },
  { name: "Antarctica", flag: "https://flagcdn.com/aq.svg", cca2: "AQ" },
  { name: "Comoros", flag: "https://flagcdn.com/km.svg", cca2: "KM" },
  { name: "Kosovo", flag: "https://flagcdn.com/xk.svg", cca2: "XK" },
  { name: "Moldova", flag: "https://flagcdn.com/md.svg", cca2: "MD" },
  { name: "Kyrgyzstan", flag: "https://flagcdn.com/kg.svg", cca2: "KG" },
  { name: "Cape Verde", flag: "https://flagcdn.com/cv.svg", cca2: "CV" },
  { name: "United States", flag: "https://flagcdn.com/us.svg", cca2: "US" },
  { name: "Venezuela", flag: "https://flagcdn.com/ve.svg", cca2: "VE" },
  {
    name: "Pitcairn Islands",
    flag: "https://flagcdn.com/pn.svg",
    cca2: "PN",
  },
  { name: "Mayotte", flag: "https://flagcdn.com/yt.svg", cca2: "YT" },
  { name: "Timor-Leste", flag: "https://flagcdn.com/tl.svg", cca2: "TL" },
  { name: "Solomon Islands", flag: "https://flagcdn.com/sb.svg", cca2: "SB" },
  {
    name: "Saint Pierre and Miquelon",
    flag: "https://flagcdn.com/pm.svg",
    cca2: "PM",
  },
  { name: "Ecuador", flag: "https://flagcdn.com/ec.svg", cca2: "EC" },
  { name: "Malta", flag: "https://flagcdn.com/mt.svg", cca2: "MT" },
  {
    name: "Central African Republic",
    flag: "https://flagcdn.com/cf.svg",
    cca2: "CF",
  },
  { name: "Tonga", flag: "https://flagcdn.com/to.svg", cca2: "TO" },
  { name: "Greece", flag: "https://flagcdn.com/gr.svg", cca2: "GR" },
  { name: "Austria", flag: "https://flagcdn.com/at.svg", cca2: "AT" },
  {
    name: "Saint Kitts and Nevis",
    flag: "https://flagcdn.com/kn.svg",
    cca2: "KN",
  },
  { name: "Nigeria", flag: "https://flagcdn.com/ng.svg", cca2: "NG" },
  { name: "Niue", flag: "https://flagcdn.com/nu.svg", cca2: "NU" },
  { name: "Czechia", flag: "https://flagcdn.com/cz.svg", cca2: "CZ" },
  { name: "San Marino", flag: "https://flagcdn.com/sm.svg", cca2: "SM" },
  {
    name: "Caribbean Netherlands",
    flag: "https://flagcdn.com/bq.svg",
    cca2: "BQ",
  },
  { name: "Qatar", flag: "https://flagcdn.com/qa.svg", cca2: "QA" },
  {
    name: "Wallis and Futuna",
    flag: "https://flagcdn.com/wf.svg",
    cca2: "WF",
  },
  { name: "Guatemala", flag: "https://flagcdn.com/gt.svg", cca2: "GT" },
  { name: "Tunisia", flag: "https://flagcdn.com/tn.svg", cca2: "TN" },
  { name: "Bhutan", flag: "https://flagcdn.com/bt.svg", cca2: "BT" },
  { name: "Macau", flag: "https://flagcdn.com/mo.svg", cca2: "MO" },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    flag: "https://flagcdn.com/sh.svg",
    cca2: "SH",
  },
  { name: "Samoa", flag: "https://flagcdn.com/ws.svg", cca2: "WS" },
  { name: "Tajikistan", flag: "https://flagcdn.com/tj.svg", cca2: "TJ" },
  { name: "Western Sahara", flag: "https://flagcdn.com/eh.svg", cca2: "EH" },
  { name: "Israel", flag: "https://flagcdn.com/il.svg", cca2: "IL" },
  { name: "Somalia", flag: "https://flagcdn.com/so.svg", cca2: "SO" },
  {
    name: "Saint Barthélemy",
    flag: "https://flagcdn.com/bl.svg",
    cca2: "BL",
  },
  { name: "Guernsey", flag: "https://flagcdn.com/gg.svg", cca2: "GG" },
  {
    name: "Turks and Caicos Islands",
    flag: "https://flagcdn.com/tc.svg",
    cca2: "TC",
  },
  { name: "Finland", flag: "https://flagcdn.com/fi.svg", cca2: "FI" },
  { name: "Lesotho", flag: "https://flagcdn.com/ls.svg", cca2: "LS" },
  { name: "Russia", flag: "https://flagcdn.com/ru.svg", cca2: "RU" },
  { name: "Ireland", flag: "https://flagcdn.com/ie.svg", cca2: "IE" },
  { name: "Azerbaijan", flag: "https://flagcdn.com/az.svg", cca2: "AZ" },
  { name: "Jamaica", flag: "https://flagcdn.com/jm.svg", cca2: "JM" },
  { name: "Eswatini", flag: "https://flagcdn.com/sz.svg", cca2: "SZ" },
  { name: "Gabon", flag: "https://flagcdn.com/ga.svg", cca2: "GA" },
  { name: "Cambodia", flag: "https://flagcdn.com/kh.svg", cca2: "KH" },
  { name: "Saudi Arabia", flag: "https://flagcdn.com/sa.svg", cca2: "SA" },
  { name: "Micronesia", flag: "https://flagcdn.com/fm.svg", cca2: "FM" },
  { name: "North Korea", flag: "https://flagcdn.com/kp.svg", cca2: "KP" },
  {
    name: "Equatorial Guinea",
    flag: "https://flagcdn.com/gq.svg",
    cca2: "GQ",
  },
  { name: "Greenland", flag: "https://flagcdn.com/gl.svg", cca2: "GL" },
  { name: "Mexico", flag: "https://flagcdn.com/mx.svg", cca2: "MX" },
  { name: "Brazil", flag: "https://flagcdn.com/br.svg", cca2: "BR" },
  { name: "Nauru", flag: "https://flagcdn.com/nr.svg", cca2: "NR" },
  { name: "Iran", flag: "https://flagcdn.com/ir.svg", cca2: "IR" },
  { name: "Angola", flag: "https://flagcdn.com/ao.svg", cca2: "AO" },
  { name: "Aruba", flag: "https://flagcdn.com/aw.svg", cca2: "AW" },
  {
    name: "Cocos (Keeling) Islands",
    flag: "https://flagcdn.com/cc.svg",
    cca2: "CC",
  },
  { name: "Myanmar", flag: "https://flagcdn.com/mm.svg", cca2: "MM" },
  { name: "Egypt", flag: "https://flagcdn.com/eg.svg", cca2: "EG" },
  { name: "Italy", flag: "https://flagcdn.com/it.svg", cca2: "IT" },
  { name: "Australia", flag: "https://flagcdn.com/au.svg", cca2: "AU" },
  { name: "Botswana", flag: "https://flagcdn.com/bw.svg", cca2: "BW" },
  { name: "Vatican City", flag: "https://flagcdn.com/va.svg", cca2: "VA" },
  { name: "Réunion", flag: "https://flagcdn.com/re.svg", cca2: "RE" },
  { name: "Liberia", flag: "https://flagcdn.com/lr.svg", cca2: "LR" },
  { name: "Portugal", flag: "https://flagcdn.com/pt.svg", cca2: "PT" },
  { name: "Anguilla", flag: "https://flagcdn.com/ai.svg", cca2: "AI" },
  { name: "Syria", flag: "https://flagcdn.com/sy.svg", cca2: "SY" },
  { name: "Denmark", flag: "https://flagcdn.com/dk.svg", cca2: "DK" },
  { name: "Albania", flag: "https://flagcdn.com/al.svg", cca2: "AL" },
  { name: "Slovakia", flag: "https://flagcdn.com/sk.svg", cca2: "SK" },
  { name: "Curaçao", flag: "https://flagcdn.com/cw.svg", cca2: "CW" },
  { name: "Zambia", flag: "https://flagcdn.com/zm.svg", cca2: "ZM" },
  {
    name: "São Tomé and Príncipe",
    flag: "https://flagcdn.com/st.svg",
    cca2: "ST",
  },
  { name: "Bahamas", flag: "https://flagcdn.com/bs.svg", cca2: "BS" },
  { name: "Netherlands", flag: "https://flagcdn.com/nl.svg", cca2: "NL" },
  { name: "American Samoa", flag: "https://flagcdn.com/as.svg", cca2: "AS" },
  { name: "Bolivia", flag: "https://flagcdn.com/bo.svg", cca2: "BO" },
  {
    name: "British Indian Ocean Territory",
    flag: "https://flagcdn.com/io.svg",
    cca2: "IO",
  },
  { name: "Germany", flag: "https://flagcdn.com/de.svg", cca2: "DE" },
  { name: "Eritrea", flag: "https://flagcdn.com/er.svg", cca2: "ER" },
  { name: "Estonia", flag: "https://flagcdn.com/ee.svg", cca2: "EE" },
  { name: "Mali", flag: "https://flagcdn.com/ml.svg", cca2: "ML" },
  { name: "Kuwait", flag: "https://flagcdn.com/kw.svg", cca2: "KW" },
  { name: "DR Congo", flag: "https://flagcdn.com/cd.svg", cca2: "CD" },
  { name: "Hungary", flag: "https://flagcdn.com/hu.svg", cca2: "HU" },
  { name: "Libya", flag: "https://flagcdn.com/ly.svg", cca2: "LY" },
  { name: "Montenegro", flag: "https://flagcdn.com/me.svg", cca2: "ME" },
  { name: "Paraguay", flag: "https://flagcdn.com/py.svg", cca2: "PY" },
  { name: "Peru", flag: "https://flagcdn.com/pe.svg", cca2: "PE" },
  { name: "Burundi", flag: "https://flagcdn.com/bi.svg", cca2: "BI" },
  { name: "Laos", flag: "https://flagcdn.com/la.svg", cca2: "LA" },
  { name: "South Sudan", flag: "https://flagcdn.com/ss.svg", cca2: "SS" },
  { name: "Cayman Islands", flag: "https://flagcdn.com/ky.svg", cca2: "KY" },
  { name: "North Macedonia", flag: "https://flagcdn.com/mk.svg", cca2: "MK" },
  { name: "Morocco", flag: "https://flagcdn.com/ma.svg", cca2: "MA" },
  { name: "Lebanon", flag: "https://flagcdn.com/lb.svg", cca2: "LB" },
  { name: "Åland Islands", flag: "https://flagcdn.com/ax.svg", cca2: "AX" },
  { name: "Guinea", flag: "https://flagcdn.com/gn.svg", cca2: "GN" },
  { name: "Nicaragua", flag: "https://flagcdn.com/ni.svg", cca2: "NI" },
  { name: "Guadeloupe", flag: "https://flagcdn.com/gp.svg", cca2: "GP" },
  { name: "Sri Lanka", flag: "https://flagcdn.com/lk.svg", cca2: "LK" },
  {
    name: "Heard Island and McDonald Islands",
    flag: "https://flagcdn.com/hm.svg",
    cca2: "HM",
  },
  { name: "China", flag: "https://flagcdn.com/cn.svg", cca2: "CN" },
  { name: "Bahrain", flag: "https://flagcdn.com/bh.svg", cca2: "BH" },
  {
    name: "Marshall Islands",
    flag: "https://flagcdn.com/mh.svg",
    cca2: "MH",
  },
  { name: "Ukraine", flag: "https://flagcdn.com/ua.svg", cca2: "UA" },
  { name: "South Africa", flag: "https://flagcdn.com/za.svg", cca2: "ZA" },
  {
    name: "Saint Vincent and the Grenadines",
    flag: "https://flagcdn.com/vc.svg",
    cca2: "VC",
  },
  { name: "Seychelles", flag: "https://flagcdn.com/sc.svg", cca2: "SC" },
  {
    name: "Dominican Republic",
    flag: "https://flagcdn.com/do.svg",
    cca2: "DO",
  },
  { name: "Indonesia", flag: "https://flagcdn.com/id.svg", cca2: "ID" },
  { name: "Malawi", flag: "https://flagcdn.com/mw.svg", cca2: "MW" },
  { name: "Cameroon", flag: "https://flagcdn.com/cm.svg", cca2: "CM" },
  { name: "Madagascar", flag: "https://flagcdn.com/mg.svg", cca2: "MG" },
  { name: "Kiribati", flag: "https://flagcdn.com/ki.svg", cca2: "KI" },
  { name: "Fiji", flag: "https://flagcdn.com/fj.svg", cca2: "FJ" },
  {
    name: "French Polynesia",
    flag: "https://flagcdn.com/pf.svg",
    cca2: "PF",
  },
  { name: "Pakistan", flag: "https://flagcdn.com/pk.svg", cca2: "PK" },
  { name: "Faroe Islands", flag: "https://flagcdn.com/fo.svg", cca2: "FO" },
  { name: "Suriname", flag: "https://flagcdn.com/sr.svg", cca2: "SR" },
  { name: "Djibouti", flag: "https://flagcdn.com/dj.svg", cca2: "DJ" },
  { name: "Gambia", flag: "https://flagcdn.com/gm.svg", cca2: "GM" },
  { name: "Mongolia", flag: "https://flagcdn.com/mn.svg", cca2: "MN" },
  { name: "Zimbabwe", flag: "https://flagcdn.com/zw.svg", cca2: "ZW" },
  { name: "Iceland", flag: "https://flagcdn.com/is.svg", cca2: "IS" },
  { name: "Haiti", flag: "https://flagcdn.com/ht.svg", cca2: "HT" },
  { name: "Romania", flag: "https://flagcdn.com/ro.svg", cca2: "RO" },
  { name: "Costa Rica", flag: "https://flagcdn.com/cr.svg", cca2: "CR" },
  { name: "Croatia", flag: "https://flagcdn.com/hr.svg", cca2: "HR" },
  { name: "Vietnam", flag: "https://flagcdn.com/vn.svg", cca2: "VN" },
  { name: "South Korea", flag: "https://flagcdn.com/kr.svg", cca2: "KR" },
  { name: "Norfolk Island", flag: "https://flagcdn.com/nf.svg", cca2: "NF" },
  { name: "Canada", flag: "https://flagcdn.com/ca.svg", cca2: "CA" },
  { name: "Liechtenstein", flag: "https://flagcdn.com/li.svg", cca2: "LI" },
  { name: "Monaco", flag: "https://flagcdn.com/mc.svg", cca2: "MC" },
  { name: "Puerto Rico", flag: "https://flagcdn.com/pr.svg", cca2: "PR" },
  { name: "Tuvalu", flag: "https://flagcdn.com/tv.svg", cca2: "TV" },
  { name: "French Guiana", flag: "https://flagcdn.com/gf.svg", cca2: "GF" },
  { name: "Saint Martin", flag: "https://flagcdn.com/mf.svg", cca2: "MF" },
  { name: "Mauritius", flag: "https://flagcdn.com/mu.svg", cca2: "MU" },
  { name: "South Georgia", flag: "https://flagcdn.com/gs.svg", cca2: "GS" },
  {
    name: "Papua New Guinea",
    flag: "https://flagcdn.com/pg.svg",
    cca2: "PG",
  },
  { name: "Kazakhstan", flag: "https://flagcdn.com/kz.svg", cca2: "KZ" },
  { name: "Malaysia", flag: "https://flagcdn.com/my.svg", cca2: "MY" },
  { name: "Uganda", flag: "https://flagcdn.com/ug.svg", cca2: "UG" },
  { name: "Burkina Faso", flag: "https://flagcdn.com/bf.svg", cca2: "BF" },
  { name: "Grenada", flag: "https://flagcdn.com/gd.svg", cca2: "GD" },
  { name: "Singapore", flag: "https://flagcdn.com/sg.svg", cca2: "SG" },
  { name: "Cook Islands", flag: "https://flagcdn.com/ck.svg", cca2: "CK" },
  { name: "Maldives", flag: "https://flagcdn.com/mv.svg", cca2: "MV" },
  { name: "Yemen", flag: "https://flagcdn.com/ye.svg", cca2: "YE" },
  {
    name: "United States Virgin Islands",
    flag: "https://flagcdn.com/vi.svg",
    cca2: "VI",
  },
  { name: "Jersey", flag: "https://flagcdn.com/je.svg", cca2: "JE" },
  { name: "Martinique", flag: "https://flagcdn.com/mq.svg", cca2: "MQ" },
  {
    name: "British Virgin Islands",
    flag: "https://flagcdn.com/vg.svg",
    cca2: "VG",
  },
  {
    name: "Antigua and Barbuda",
    flag: "https://flagcdn.com/ag.svg",
    cca2: "AG",
  },
  { name: "Panama", flag: "https://flagcdn.com/pa.svg", cca2: "PA" },
  { name: "Thailand", flag: "https://flagcdn.com/th.svg", cca2: "TH" },
  { name: "Sweden", flag: "https://flagcdn.com/se.svg", cca2: "SE" },
  { name: "Algeria", flag: "https://flagcdn.com/dz.svg", cca2: "DZ" },
  { name: "Mozambique", flag: "https://flagcdn.com/mz.svg", cca2: "MZ" },
  { name: "Namibia", flag: "https://flagcdn.com/na.svg", cca2: "NA" },
  { name: "Barbados", flag: "https://flagcdn.com/bb.svg", cca2: "BB" },
  {
    name: "Svalbard and Jan Mayen",
    flag: "https://flagcdn.com/sj.svg",
    cca2: "SJ",
  },
  { name: "Hong Kong", flag: "https://flagcdn.com/hk.svg", cca2: "HK" },
  { name: "Honduras", flag: "https://flagcdn.com/hn.svg", cca2: "HN" },
  { name: "Japan", flag: "https://flagcdn.com/jp.svg", cca2: "JP" },
  {
    name: "United States Minor Outlying Islands",
    flag: "https://flagcdn.com/um.svg",
    cca2: "UM",
  },
  { name: "Guam", flag: "https://flagcdn.com/gu.svg", cca2: "GU" },
  { name: "Sint Maarten", flag: "https://flagcdn.com/sx.svg", cca2: "SX" },
  { name: "Belarus", flag: "https://flagcdn.com/by.svg", cca2: "BY" },
  { name: "Bermuda", flag: "https://flagcdn.com/bm.svg", cca2: "BM" },
  {
    name: "Bosnia and Herzegovina",
    flag: "https://flagcdn.com/ba.svg",
    cca2: "BA",
  },
  { name: "Gibraltar", flag: "https://flagcdn.com/gi.svg", cca2: "GI" },
  { name: "Kenya", flag: "https://flagcdn.com/ke.svg", cca2: "KE" },
  { name: "New Zealand", flag: "https://flagcdn.com/nz.svg", cca2: "NZ" },
  {
    name: "French Southern and Antarctic Lands",
    flag: "https://flagcdn.com/tf.svg",
    cca2: "TF",
  },
  { name: "Tokelau", flag: "https://flagcdn.com/tk.svg", cca2: "TK" },
  { name: "Guyana", flag: "https://flagcdn.com/gy.svg", cca2: "GY" },
  { name: "Nepal", flag: "https://flagcdn.com/np.svg", cca2: "NP" },
  { name: "India", flag: "https://flagcdn.com/in.svg", cca2: "IN" },
  {
    name: "Trinidad and Tobago",
    flag: "https://flagcdn.com/tt.svg",
    cca2: "TT",
  },
  { name: "Luxembourg", flag: "https://flagcdn.com/lu.svg", cca2: "LU" },
  { name: "Switzerland", flag: "https://flagcdn.com/ch.svg", cca2: "CH" },
  { name: "Taiwan", flag: "https://flagcdn.com/tw.svg", cca2: "TW" },
  { name: "Iraq", flag: "https://flagcdn.com/iq.svg", cca2: "IQ" },
  { name: "Norway", flag: "https://flagcdn.com/no.svg", cca2: "NO" },
  { name: "Oman", flag: "https://flagcdn.com/om.svg", cca2: "OM" },
  { name: "United Kingdom", flag: "https://flagcdn.com/gb.svg", cca2: "GB" },
  { name: "Dominica", flag: "https://flagcdn.com/dm.svg", cca2: "DM" },
  { name: "Spain", flag: "https://flagcdn.com/es.svg", cca2: "ES" },
  { name: "Serbia", flag: "https://flagcdn.com/rs.svg", cca2: "RS" },
  { name: "Slovenia", flag: "https://flagcdn.com/si.svg", cca2: "SI" },
  { name: "Armenia", flag: "https://flagcdn.com/am.svg", cca2: "AM" },
  { name: "Niger", flag: "https://flagcdn.com/ne.svg", cca2: "NE" },
  { name: "Bouvet Island", flag: "https://flagcdn.com/bv.svg", cca2: "BV" },
  {
    name: "Christmas Island",
    flag: "https://flagcdn.com/cx.svg",
    cca2: "CX",
  },
  { name: "Colombia", flag: "https://flagcdn.com/co.svg", cca2: "CO" },
  { name: "Poland", flag: "https://flagcdn.com/pl.svg", cca2: "PL" },
  { name: "Turkey", flag: "https://flagcdn.com/tr.svg", cca2: "TR" },
  { name: "Brunei", flag: "https://flagcdn.com/bn.svg", cca2: "BN" },
  { name: "Mauritania", flag: "https://flagcdn.com/mr.svg", cca2: "MR" },
];
